spring.application.name=backend-modular-monolith
server.port=8080

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Database Configuration (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:10000/postgres?currentSchema=public}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
